import { defineConfig } from 'vitest/config';

/** Files whose behaviour is proven by the integration suite (vitest.int.config.ts) against real services. */
export const apiUnitCoverageExclude = [
  'src/**/*.test.ts',
  'src/server.ts',
  'src/**/index.ts',
  'src/types/**',
  'src/ports/adapters/s3-object-storage.ts',
  'src/ports/adapters/smtp-email.ts',
  'src/db/prisma.ts',
  'src/db/relations.ts',
  'src/db/scoping.ts',
  'src/db/encryption-extension.ts',
  'src/plugins/prisma.ts',
  'src/modules/inventory/apply-movement.ts',
  'src/plugins/auth.ts',
  'src/plugins/rate-limit.ts',
  'src/modules/auth/routes.ts',
  'src/modules/auth/session.routes.ts',
  'src/modules/auth/mfa.routes.ts',
  'src/modules/auth/login.service.ts',
  'src/modules/auth/otp.service.ts',
  'src/modules/auth/refresh.service.ts',
  'src/modules/auth/mfa.service.ts',
  'src/modules/auth/user-state.ts',
  'src/modules/auth/guards.ts',
  'src/modules/auth/security-events.ts',
  'src/modules/auth/emails.ts',
  'src/modules/staff/**',
  'src/app.ts',
  'src/lib/valkey.ts',
  'src/plugins/jobs.ts',
  'src/plugins/catalogue.ts',
  'src/jobs/boss.ts',
  'src/jobs/register.ts',
  'src/modules/catalogue/*.service.ts',
  'src/modules/catalogue/service-deps.ts',
  'src/modules/catalogue/admin-dto.ts',
  'src/modules/catalogue/queries.ts',
  'src/modules/catalogue/related.ts',
  'src/modules/catalogue/tree.ts',
  'src/modules/catalogue/routes.public.ts',
  'src/modules/media/process.job.ts',
  'src/modules/admin/*.routes.ts',
  'src/modules/admin/settings.schemas.ts',
  'src/modules/admin/stats.query.ts',
  'src/modules/inventory/adjust.service.ts',
  'src/modules/inventory/stock.query.ts',
  'src/modules/inventory/ledger.query.ts',
  'src/modules/inventory/ledger-check.job.ts',
  'src/plugins/security-counters.ts',
  'src/modules/imports/deps.ts',
  'src/modules/imports/service.ts',
  'src/modules/imports/routes.ts',
  'src/modules/imports/validate.job.ts',
  'src/modules/imports/apply.job.ts',
  'src/modules/exports/routes.ts',
  'src/modules/exports/generate.job.ts',
  'src/modules/exports/expire.ts',
  'src/modules/exports/products.export.ts',
  'src/modules/exports/orders.export.ts',
  'src/modules/exports/customers.export.ts',
  'src/modules/dpdp/**',
  'src/modules/customers/**',
  // notifications: routes and job handlers covered by integration tests
  'src/modules/notifications/send.job.ts',
  'src/modules/notifications/feedback.routes.ts',
  'src/modules/notifications/suppression.routes.ts',
  'src/modules/notifications/preview.routes.ts',
  // cart, addresses, and orders: covered by integration tests against real services
  'src/modules/cart/**',
  'src/modules/addresses/**',
  'src/modules/orders/**',
  'src/modules/payments/**',
  'src/modules/shipping/**',
  'src/modules/tax/**',
  // admin/orders: service logic covered by integration tests
  'src/modules/admin/orders/**',
  // jobs queue types are pure declarations/constants; covered indirectly via integration suite
  'src/jobs/queue.ts',
  // Shiprocket adapter: covered by msw contract tests in the integration suite
  'src/ports/adapters/shiprocket.ts',
  // Orders plugin: covered by integration tests
  'src/plugins/orders.ts',
  // Port interface files (TypeScript types only — no executable code to cover)
  'src/ports/email.ts',
  'src/ports/object-storage.ts',
  'src/ports/search.ts',
  'src/ports/shipping.ts',
];

export default defineConfig({
  test: {
    name: 'api',
    environment: 'node',
    include: ['src/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/**'],
      exclude: apiUnitCoverageExclude,
      thresholds: { lines: 80, branches: 80, functions: 80, statements: 80 },
    },
  },
});
